# Generated by Django 3.2.12 on 2024-06-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
